openapi: 3.0.0

info:
  description: real estate renting API
  version: "1.0.0"
  title: Simple properties renting API

servers:
- url: http://localhost:8080/

paths:
  /properties:
    get:
      summary: get all availble properties
      responses:
        200:
          description: a list of availble properties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/simple_property'
    post:
      summary: post a new simple property
      requestBody:
        $ref: '#/components/requestBodies/property'
      responses:
        200:
          description: add the given property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/simple_property'


  /properties/{property_id}:
    get:
      description: get property by id
      parameters:
      - $ref: '#/components/parameters/property_id'
      responses:
        200:
          description: get the specified property information with comments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commented_property'
    post:
      summary: post a new comment to the specified prperty
      parameters:
        - $ref: '#/components/parameters/property_id'
      requestBody:
        $ref: '#/components/requestBodies/comment'
      responses:
        200:
          description: add the given coomment to the specified property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'

components:

  parameters:
    property_id:
      in: path
      name: property_id
      description: the requested property id
      required: true
      schema:
        type: string

  requestBodies:
    property:
      description: property information to post
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/simple_property'

    comment:
      description: comment to post
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/comment'

  schemas:
    simple_property:
      type: object
      properties:
        property_id:
          type: string
        owner_id:
          type: string
        property_type:
          type: string
        adress:
          type: string
        rooms:
          type: integer
        area:
          type: number
        rent:
          type: number
        images:
          type: array
          items:
            type: string
      required:
      - property_id
      - owner_id
      - property_type
      - adress
      - rooms
      - area
      - rent

    comment:
      type: object
      properties:
        user_id:
          type: string
        year:
          type: integer
        rent:
          type: number
        description:
          type: string
      required:
        - user_id
        - year
        - rent

    commented_property:
      type: object
      properties:
        property:
          $ref: '#/components/schemas/simple_property'
        comments:
          type: array
          items:
            $ref: '#/components/schemas/comment'
      required:
        - property